from __future__ import annotations

from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse
from src.complexity_scanner.engine import run_scanner, country_detail
from src.complexity_scanner.methodology import METHODOLOGY

app = FastAPI(
    title="Global Economic Complexity Investment Scanner",
    version="0.1.0",
    description="Structural country and product opportunity scanner powered by economic complexity and macro data.",
)

DASHBOARD = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>Global Economic Complexity Investment Scanner</title>
<style>
:root{--bg:#05070b;--panel:#0a1017;--line:#192532;--line2:#111b25;--text:#f2f5f7;--text2:#c3ccd4;--muted:#748290;--muted2:#4f5d69;--cyan:#62dff0;--green:#70e8b4;--red:#ff7685;--amber:#e9c56f}
*{box-sizing:border-box}body{margin:0;color:var(--text);background:radial-gradient(circle at 78% -8%,rgba(98,223,240,.08),transparent 30%),linear-gradient(rgba(255,255,255,.016) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.016) 1px,transparent 1px),var(--bg);background-size:auto,48px 48px,48px 48px,auto;font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;-webkit-font-smoothing:antialiased}.shell{max-width:1480px;margin:auto;padding:0 28px 70px}.top{height:72px;border-bottom:1px solid var(--line2);display:flex;align-items:center;justify-content:space-between;gap:18px}.brandw{display:flex;align-items:center;gap:12px}.mark{width:35px;height:35px;border:1px solid #243441;border-radius:9px;display:grid;place-items:center;background:#0c141c;color:var(--cyan);font:800 10px ui-monospace,monospace}.brand{font-size:14px;font-weight:720}.sub{font:600 9px ui-monospace,monospace;color:var(--muted);text-transform:uppercase;letter-spacing:.09em;margin-top:4px}.nav{display:flex;align-items:center;gap:5px}.nav a,.btn{color:var(--muted);background:transparent;border:1px solid transparent;padding:8px 10px;border-radius:8px;text-decoration:none;cursor:pointer;font-size:12px}.nav a:hover,.btn:hover{color:var(--text2);background:#0a1118;border-color:var(--line)}.live{display:flex;align-items:center;gap:7px;border:1px solid #17333a;background:rgba(98,223,240,.045);padding:7px 10px;border-radius:999px;color:#99e6ee;font:700 9px ui-monospace,monospace;text-transform:uppercase}.dot{width:6px;height:6px;border-radius:50%;background:var(--cyan);box-shadow:0 0 13px rgba(98,223,240,.7)}
.hero{padding:34px 0 18px;display:grid;grid-template-columns:minmax(0,1.4fr) minmax(330px,.6fr);gap:16px}.box,.panel,.metric{border:1px solid var(--line);background:linear-gradient(180deg,rgba(255,255,255,.018),rgba(255,255,255,.004));border-radius:15px}.heroMain{padding:34px 36px;min-height:285px;position:relative;overflow:hidden}.heroMain:after{content:"";position:absolute;right:-180px;top:-210px;width:390px;height:390px;border:1px solid rgba(98,223,240,.1);border-radius:50%;box-shadow:0 0 0 58px rgba(98,223,240,.014),0 0 0 116px rgba(98,223,240,.008)}.kicker{color:var(--cyan);font:700 10px ui-monospace,monospace;text-transform:uppercase;letter-spacing:.15em}h1{font-size:clamp(39px,4.8vw,68px);line-height:.98;letter-spacing:-.056em;margin:22px 0 18px;max-width:930px;font-weight:720}.copy{max-width:800px;color:#98a6b2;font-size:14px;line-height:1.75}.meta{display:flex;gap:22px;flex-wrap:wrap;margin-top:26px;color:var(--muted);font:600 9px ui-monospace,monospace;text-transform:uppercase;letter-spacing:.08em}.meta strong{color:var(--text2)}.heroSide{padding:25px;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden}.heroSide:before{content:"";position:absolute;top:0;left:0;right:0;height:2px;background:linear-gradient(90deg,var(--cyan),transparent 72%)}
.label{font:650 9px ui-monospace,monospace;color:var(--muted);text-transform:uppercase;letter-spacing:.105em}.big{font:700 48px/1 ui-monospace,monospace;letter-spacing:-.06em;margin:12px 0 7px}.small{font-size:10px;color:var(--muted);line-height:1.55}.rankline{margin-top:22px;padding-top:16px;border-top:1px solid var(--line)}.rankname{font-size:18px;font-weight:700;margin-top:7px}.rankscore{color:var(--cyan);font:650 12px ui-monospace,monospace;margin-top:7px}.controls{display:grid;grid-template-columns:1.2fr .65fr .65fr .65fr auto;gap:9px;margin-bottom:16px}.control{border:1px solid var(--line);background:#080d13;border-radius:10px;padding:10px 12px;color:var(--text2);font-size:11px;outline:none}.control option{background:#090e14}
.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:16px}.metric{padding:16px 17px}.metricVal{font:650 23px ui-monospace,monospace;letter-spacing:-.04em;margin-top:12px}.metricSub{font-size:9px;color:var(--muted2);margin-top:6px}.panel{padding:20px;margin-bottom:16px}.panelHead{display:flex;justify-content:space-between;align-items:flex-start;gap:18px;margin-bottom:17px}.title{font-size:14px;font-weight:680}.desc{font-size:10px;color:var(--muted);line-height:1.45;margin-top:5px}.tag{border:1px solid var(--line);border-radius:7px;padding:6px 8px;color:var(--muted);font:650 9px ui-monospace,monospace;text-transform:uppercase}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:1080px}th{font:600 9px ui-monospace,monospace;color:var(--muted);text-transform:uppercase;letter-spacing:.08em;text-align:right;padding:10px;border-bottom:1px solid var(--line)}td{font:500 11px ui-monospace,monospace;color:#c4ced6;text-align:right;padding:13px 10px;border-bottom:1px solid var(--line2)}th:first-child,td:first-child{text-align:left}tbody tr{cursor:pointer}tbody tr:hover{background:rgba(98,223,240,.026)}.countryCell{display:flex;align-items:center;gap:11px;font-family:Inter,sans-serif}.rank{width:25px;color:var(--muted);font:650 10px ui-monospace,monospace}.iso{width:31px;height:27px;border:1px solid #1b2c39;border-radius:7px;display:grid;place-items:center;background:#0b141c;color:#9ccbd1;font:700 8px ui-monospace,monospace}.countryName{font-size:12px;color:var(--text);font-weight:700}.region{font-size:9px;color:var(--muted);margin-top:2px}.score{color:var(--cyan);font-weight:750}.pos{color:var(--green)}.neg,.flag{color:var(--red)}.badge{display:inline-flex;border:1px solid #24313e;border-radius:999px;padding:5px 7px;font:650 8px ui-monospace,monospace;text-transform:uppercase;color:#9cabb7}.leader{color:#a5eaf0;border-color:#23505a}.compounder{color:#9fe2c5;border-color:#234638}.watchlist{color:#e6ca91;border-color:#493e25}.bar{height:4px;background:#121d27;border-radius:99px;overflow:hidden;margin-top:5px}.bar span{display:block;height:100%;background:linear-gradient(90deg,#2cb5ca,var(--cyan))}
.drawer{position:fixed;inset:0;background:rgba(1,4,7,.66);backdrop-filter:blur(5px);display:none;justify-content:flex-end;z-index:20}.drawer.open{display:flex}.drawerPanel{width:min(720px,94vw);height:100%;overflow:auto;background:#070c12;border-left:1px solid #21303d;padding:28px}.drawerTop{display:flex;justify-content:space-between;align-items:center}.close{border:1px solid var(--line);background:#0b1219;color:var(--muted);border-radius:8px;padding:8px 10px;cursor:pointer}.countryHero{padding:28px 0 18px;border-bottom:1px solid var(--line)}.countryTitle{font-size:34px;font-weight:730;letter-spacing:-.04em}.countryMeta{margin-top:8px;color:var(--muted);font:600 10px ui-monospace,monospace}.detailMetrics{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:16px 0}.dstat{border:1px solid var(--line2);background:#090f15;padding:12px;border-radius:9px}.dval{font:650 16px ui-monospace,monospace;margin-top:7px}.sectionTitle{font-size:13px;font-weight:680;margin:25px 0 11px}.opp{border:1px solid var(--line2);border-radius:10px;padding:12px 13px;margin:8px 0;background:#080e14}.oppTop{display:flex;justify-content:space-between;gap:15px}.oppName{font-size:11px;font-weight:650;color:var(--text2)}.oppCode{font:600 9px ui-monospace,monospace;color:var(--muted);margin-top:4px}.oppScore{font:700 12px ui-monospace,monospace;color:var(--cyan)}.oppMeta{display:flex;gap:14px;flex-wrap:wrap;margin-top:10px;color:var(--muted);font:550 9px ui-monospace,monospace}.loading,.error{border:1px solid var(--line);background:#090f15;padding:22px;border-radius:12px;color:var(--muted);font:500 11px/1.65 ui-monospace,monospace}.error{border-color:#52303a;color:#ffb8c0}.footer{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap;color:var(--muted2);font:550 9px ui-monospace,monospace;text-transform:uppercase}
@media(max-width:1000px){.hero{grid-template-columns:1fr}.controls{grid-template-columns:1fr 1fr}.metrics{grid-template-columns:1fr 1fr}}@media(max-width:650px){.shell{padding:0 14px 45px}.top{height:auto;padding:14px 0}.sub,.nav a{display:none}.heroMain{padding:24px 20px}h1{font-size:42px}.metrics,.controls,.detailMetrics{grid-template-columns:1fr}.drawerPanel{padding:20px}}
</style></head><body><div class="shell"><header class="top"><div class="brandw"><div class="mark">EC</div><div><div class="brand">Global Economic Complexity Investment Scanner</div><div class="sub">Structural Intelligence Platform</div></div></div><div class="nav"><a href="/methodology">Methodology</a><a href="/docs">API</a><button class="btn" id="refreshBtn">Refresh</button><div class="live"><span class="dot"></span>Scanner live</div></div></header>
<section class="hero"><div class="box heroMain"><div class="kicker">Productive capabilities · country allocation · adjacent sectors</div><h1>Find economies building the capabilities that compound.</h1><div class="copy">A structural investment scanner combining economic complexity, capability momentum and macro investability to surface countries and product adjacencies worth deeper research.</div><div class="meta"><span>Core signal <strong>Economic complexity</strong></span><span>Macro layer <strong>World Bank</strong></span><span>Output <strong>Structural ranking, not probability</strong></span></div></div><aside class="box heroSide"><div><div class="label">Countries scored</div><div class="big" id="universe">--</div><div class="small" id="tradeYear">Loading current research universe...</div></div><div class="rankline"><div class="label">Top structural opportunity</div><div class="rankname" id="topCountry">--</div><div class="rankscore" id="topScore">--</div></div></aside></section>
<div class="controls"><input id="search" class="control" placeholder="Search country, ISO or investment lens"><select id="region" class="control"><option value="">All regions</option></select><select id="classFilter" class="control"><option value="">All classifications</option><option>Structural Leader</option><option>Emerging Compounder</option><option>Watchlist</option><option>Early / Fragile</option></select><select id="sort" class="control"><option value="score">Sort: Structural score</option><option value="eci">Sort: ECI</option><option value="momentum">Sort: ECI momentum</option><option value="growth">Sort: GDP growth</option></select><button class="btn" id="clearBtn" style="border-color:var(--line);background:#080d13">Clear</button></div><main id="content"><div class="loading">INITIALIZING ECONOMIC COMPLEXITY + MACRO DATA...</div></main><footer class="footer"><span>Research use only · not investment advice</span><span>Harvard Growth Lab Atlas · World Bank Indicators</span></footer></div>
<div class="drawer" id="drawer"><div class="drawerPanel"><div class="drawerTop"><div class="label">Country structural intelligence</div><button class="close" id="closeDrawer">Close</button></div><div id="drawerContent" class="loading" style="margin-top:20px">Loading...</div></div></div>
<script>
const $=id=>document.getElementById(id),pct=x=>x==null?'—':Number(x).toFixed(1)+'%',num=(x,d=2)=>x==null?'—':Number(x).toFixed(d),esc=s=>String(s??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m])),pos=x=>Number(x)>0?'pos':Number(x)<0?'neg':'',badgeClass=s=>s==='Structural Leader'?'leader':s==='Emerging Compounder'?'compounder':s==='Watchlist'?'watchlist':'';const money=x=>{if(x==null)return'—';const n=Number(x);if(n>=1e12)return'$'+(n/1e12).toFixed(2)+'T';if(n>=1e9)return'$'+(n/1e9).toFixed(1)+'B';if(n>=1e6)return'$'+(n/1e6).toFixed(1)+'M';return'$'+n.toFixed(0)};let DATA=null;
function filtered(){if(!DATA)return[];const q=$('search').value.trim().toLowerCase(),region=$('region').value,cf=$('classFilter').value;let rows=DATA.countries.filter(x=>(!region||x.region===region)&&(!cf||x.classification===cf)&&(!q||[x.country,x.iso3,x.investment_lens].join(' ').toLowerCase().includes(q)));const s=$('sort').value;rows.sort((a,b)=>s==='eci'?(b.eci??-99)-(a.eci??-99):s==='momentum'?(b.eci_change_5y??-99)-(a.eci_change_5y??-99):s==='growth'?(b.gdp_growth??-99)-(a.gdp_growth??-99):(b.structural_score??-99)-(a.structural_score??-99));return rows}
function render(){const rows=filtered(),leaders=DATA.countries.filter(x=>x.classification==='Structural Leader').length,compounders=DATA.countries.filter(x=>x.classification==='Emerging Compounder').length,positive=DATA.countries.filter(x=>(x.eci_change_5y??0)>0).length,scores=DATA.countries.map(x=>x.structural_score).filter(x=>x!=null).sort((a,b)=>a-b),med=scores.length?scores[Math.floor(scores.length/2)]:null;const body=rows.map((x,i)=>`<tr onclick="openCountry('${x.iso3}')"><td><div class="countryCell"><div class="rank">${String(i+1).padStart(2,'0')}</div><div class="iso">${esc(x.iso3)}</div><div><div class="countryName">${esc(x.country)}</div><div class="region">${esc(x.region||'Region unavailable')} · ${esc(x.investment_lens||'')}</div></div></div></td><td><span class="score">${num(x.structural_score,1)}</span><div class="bar"><span style="width:${Math.max(0,Math.min(100,x.structural_score||0))}%"></span></div></td><td><span class="badge ${badgeClass(x.classification)}">${esc(x.classification)}</span></td><td>${num(x.eci,2)}</td><td class="${pos(x.eci_change_5y)}">${x.eci_change_5y==null?'—':(x.eci_change_5y>=0?'+':'')+num(x.eci_change_5y,2)}</td><td class="${pos(x.gdp_growth)}">${pct(x.gdp_growth)}</td><td>${pct(x.fdi_gdp)}</td><td>${pct(x.inflation)}</td><td>${pct(x.market_cap_gdp)}</td><td>${x.risk_flags?.length?`<span class="flag">${x.risk_flags.length} flag${x.risk_flags.length>1?'s':''}</span>`:'Clear'}</td></tr>`).join('');$('content').innerHTML=`<section class="metrics"><div class="metric"><div class="label">Structural leaders</div><div class="metricVal">${leaders}</div><div class="metricSub">Score ≥ 80</div></div><div class="metric"><div class="label">Emerging compounders</div><div class="metricVal">${compounders}</div><div class="metricSub">Score 65–79.9</div></div><div class="metric"><div class="label">Positive ECI momentum</div><div class="metricVal">${positive}</div><div class="metricSub">Complexity rising</div></div><div class="metric"><div class="label">Median structural score</div><div class="metricVal">${num(med,1)}</div><div class="metricSub">Cross-sectional median</div></div></section><section class="panel"><div class="panelHead"><div><div class="title">Global Structural Opportunity Leaderboard</div><div class="desc">Economic complexity + capability momentum + macro investability. Click any country for product adjacencies.</div></div><div class="tag">${rows.length} visible</div></div><div class="tablewrap"><table><thead><tr><th>Country</th><th>Score</th><th>Class</th><th>ECI</th><th>5Y Δ ECI</th><th>GDP growth</th><th>FDI/GDP</th><th>Inflation</th><th>Mkt cap/GDP</th><th>Risk</th></tr></thead><tbody>${body||'<tr><td colspan="10">No countries match.</td></tr>'}</tbody></table></div></section>`}
async function load(force=false){try{const r=await fetch('/snapshot'+(force?'?refresh=true':''));if(!r.ok)throw new Error('HTTP '+r.status);DATA=await r.json();$('universe').textContent=DATA.universe_size;$('tradeYear').textContent='Trade year '+DATA.trade_year+' · '+DATA.score_semantics;const top=DATA.top_five?.[0];$('topCountry').textContent=top?.country||'—';$('topScore').textContent=top?num(top.structural_score,1)+' / 100 · '+top.classification:'—';$('region').innerHTML='<option value="">All regions</option>'+DATA.regions.map(x=>`<option>${esc(x)}</option>`).join('');render()}catch(e){$('content').innerHTML=`<div class="error"><b>Scanner data unavailable.</b><br>${esc(e.message)}<br><br>The application refuses to substitute fabricated economic-complexity data when the upstream provider is unavailable.</div>`}}
async function openCountry(iso){$('drawer').classList.add('open');$('drawerContent').className='loading';$('drawerContent').innerHTML='LOADING PRODUCT SPACE + ADJACENCIES...';try{const r=await fetch('/country/'+iso);if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json(),c=d.country,stats=[['Structural score',num(c.structural_score,1)],['ECI',num(c.eci,2)],['5Y Δ ECI',(c.eci_change_5y??0)>=0?'+'+num(c.eci_change_5y,2):num(c.eci_change_5y,2)],['GDP growth',pct(c.gdp_growth)],['FDI / GDP',pct(c.fdi_gdp)],['Inflation',pct(c.inflation)]].map(([k,v])=>`<div class="dstat"><div class="label">${k}</div><div class="dval">${v}</div></div>`).join(''),opp=(d.adjacent_opportunities||[]).map(x=>`<div class="opp"><div class="oppTop"><div><div class="oppName">${esc(x.nameEn||'Unnamed product')}</div><div class="oppCode">HS ${esc(x.code||'')} · ${esc(x.opportunity_type||'Capability adjacency')}</div></div><div class="oppScore">${num(x.opportunity_score,1)}</div></div><div class="oppMeta"><span>RCA ${num(x.exportRca,2)}</span><span>Distance ${num(x.distance,2)}</span><span>PCI ${num(x.normalizedPci,2)}</span>${x.greenProduct?'<span class="pos">Green product</span>':''}</div></div>`).join(''),adv=(d.revealed_advantages||[]).map(x=>`<div class="opp"><div class="oppTop"><div><div class="oppName">${esc(x.nameEn||'Unnamed product')}</div><div class="oppCode">HS ${esc(x.code||'')}</div></div><div class="oppScore">RCA ${num(x.exportRca,2)}</div></div><div class="oppMeta"><span>Exports ${money(x.exportValue)}</span></div></div>`).join(''),flags=(c.risk_flags||[]).length?c.risk_flags.map(x=>`<span class="badge" style="margin:0 5px 5px 0;color:var(--red)">${esc(x)}</span>`).join(''):'<span class="small">No configured structural risk flags.</span>';$('drawerContent').className='';$('drawerContent').innerHTML=`<div class="countryHero"><div class="countryTitle">${esc(c.country)}</div><div class="countryMeta">${esc(c.iso3)} · ${esc(c.region||'')} · ${esc(c.classification)} · ${esc(c.investment_lens||'')}</div></div><div class="detailMetrics">${stats}</div><div class="sectionTitle">Risk monitor</div>${flags}<div class="sectionTitle">Adjacent high-complexity opportunities</div>${opp||'<div class="small">No product adjacency data returned.</div>'}<div class="sectionTitle">Current revealed advantages</div>${adv||'<div class="small">No revealed-advantage data returned.</div>'}<div class="small" style="margin-top:22px">${esc(d.product_methodology)}</div>`}catch(e){$('drawerContent').className='error';$('drawerContent').innerHTML='Country detail unavailable: '+esc(e.message)}}
['search','region','classFilter','sort'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));$('clearBtn').onclick=()=>{$('search').value='';$('region').value='';$('classFilter').value='';$('sort').value='score';render()};$('refreshBtn').onclick=()=>load(true);$('closeDrawer').onclick=()=>$('drawer').classList.remove('open');$('drawer').addEventListener('click',e=>{if(e.target===$('drawer'))$('drawer').classList.remove('open')});load();
</script></body></html>'''

@app.get("/", response_class=HTMLResponse)
def dashboard(): return DASHBOARD

@app.get("/health")
def health(): return {"status":"ok","service":"global-economic-complexity-scanner"}

@app.get("/snapshot")
def snapshot(refresh: bool = False):
    try: return run_scanner(force=refresh)
    except Exception as exc: raise HTTPException(status_code=503, detail=str(exc)) from exc

@app.get("/countries")
def countries(refresh: bool = False):
    d = snapshot(refresh=refresh)
    return {"trade_year":d["trade_year"],"score_semantics":d["score_semantics"],"countries":d["countries"]}

@app.get("/country/{iso3}")
def country(iso3: str, refresh: bool = False):
    try: return country_detail(iso3, force=refresh)
    except KeyError as exc: raise HTTPException(status_code=404, detail=str(exc)) from exc
    except Exception as exc: raise HTTPException(status_code=503, detail=str(exc)) from exc

@app.get("/methodology")
def methodology(): return METHODOLOGY
